ENTRY = {"PENDING","OBSERVING","ACTIVE","ARMED_COUNTDOWN"}
INTERMEDIATE = {"RUNNING","REACHED_TARGET","VERIFY_ACTUAL_OUTCOME","DELAYED","CHANGED"}
OUTCOME_FINAL = {"OCCURRED","NOT_VERIFIED","CANCELLED"}
ARCHIVAL_FINAL = {"ARCHIVED"}

VALID_TRANSITIONS = {
    "PENDING": {"OBSERVING","ACTIVE","ARMED_COUNTDOWN","ARCHIVED"},
    "OBSERVING": {"ACTIVE","ARMED_COUNTDOWN","ARCHIVED"},
    "ACTIVE": {"RUNNING","ARCHIVED"},
    "ARMED_COUNTDOWN": {"ARMED_COUNTDOWN","RUNNING","CANCELLED","ARCHIVED"},
    "RUNNING": {"RUNNING","REACHED_TARGET","DELAYED","CANCELLED","ARCHIVED"},
    "REACHED_TARGET": {"REACHED_TARGET","VERIFY_ACTUAL_OUTCOME","ARCHIVED"},
    "VERIFY_ACTUAL_OUTCOME": {"VERIFY_ACTUAL_OUTCOME","OCCURRED","CHANGED","DELAYED","CANCELLED","NOT_VERIFIED","ARCHIVED"},
    "DELAYED": {"DELAYED","RUNNING","CANCELLED","ARCHIVED"},
    "CHANGED": {"CHANGED","ACTIVE","ARCHIVED"},
    "OCCURRED": {"OCCURRED","ARCHIVED"},
    "NOT_VERIFIED": {"NOT_VERIFIED","ARCHIVED"},
    "CANCELLED": {"CANCELLED","ARCHIVED"},
    "ARCHIVED": set(),
}

def validate_state_transition(from_state: str, to_state: str) -> bool:
    return to_state in VALID_TRANSITIONS.get(from_state, set())
